### ISSUE TITLE
SecurityContextInterface fix doesn't seem to work

### ISSUE THREAD

**Issue by vbjordan** [hautelook/SentryBundle#10]
Upgraded from 0.1.8 to 0.1.9 which fixes the deprecated SecurityContextInterface bug:

https://github.com/hautelook/SentryBundle/commit/0efe23919122d59489fa1f427f2e5481c269eded
https://github.com/hautelook/SentryBundle/commit/3fd2520ddd045b8b56216fcf3e281cb1042ac314

However 0.1.9 pulls down hautelook/sentry-client ~0.1 which doesn't seem to support the object in the constructor:

https://github.com/hautelook/sentry-client/blob/0.1.3/src/Hautelook/SentryClient/Request/Factory/SymfonyUserFactory.php#L19

Master does though:

https://github.com/hautelook/sentry-client/blob/master/src/Hautelook/SentryClient/Request/Factory/SymfonyUserFactory.php#L18

Is there a workaround for this?

**Comment by vbjordan** [comment]
Bumping this...

Any plans to fix this or am I missing something here?

**Comment by hjr3** [comment]
I think `0.1.9` is a busted release. I tagged a new `0.1.10` release with the downstream dependency updated. My wifi on the train is a little slow, but I will confirm that this is working in my project correctly as well.

**Comment by vbjordan** [comment]
Seems to work, thanks a lot.
