### ISSUE TITLE
Request object not available in SymfonyHttpFactory

### ISSUE THREAD

**Issue by martijngastkemper** [hautelook/SentryBundle#12]
The request object is not available in SymfonyHttpFactory. No exception is thrown, but request information isn't send to Sentry because of this.

As of Symfony 2.7 the request service isn't available ([source](http://symfony.com/blog/new-in-symfony-2-7-dependency-injection-improvements#deprecated-synchronized-services)). This bundle depends on this request service. [Symfony documentation has a page](http://symfony.com/doc/2.8/book/service_container.html#injecting-the-request) with the proper way of doing this.

Due to vacation I'm not able to create a PR. Maybe somebody else has time to create a PR.

**Comment by martijngastkemper** [comment]
Thanks @NielsJanssen, @muub and @hjr3 for solving this problem despite all the vacations ☀️.

**Comment by NielsJanssen** [comment]
@hjr3 This issue can be closed, could you also tag new releases for this bundle and the client?

**Comment by martijngastkemper** [comment]
@muub @adrienbrault Can you please tag a new release for this bundle and the client? I would like to use proper versions instead of a hash to install the right version via Composer.

**Comment by muub** [comment]
@martijngastkemper I have created a new release.

**Comment by martijngastkemper** [comment]
This issue is resolved.
